### PR TITLE
Fix: use type parameter names before bounds in error messages

### LINKED ISSUE #1263: Type parameter name missing in the error message
#1227 introduces a new jtreg test with generics.

The error message of required type does not show the name of the type parameter. 

Figure out why and fix the issue.

_Originally posted by @Ao-senXiong in https://github.com/eisop/checker-framework/pull/1227#discussion_r2150722695_

### PR DESCRIPTION
**Pull request by Ao-senXiong**
Fixes #1263

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 1]
```diff
@@ -3785,23 +3785,25 @@ protected void checkTypeArguments(
...
                 FoundRequired fr = FoundRequired.of(typeArg, bounds);
                 checker.reportError(
                         reportErrorToTree,
                         "type.argument.type.incompatible",
-                        paramNames.get(i),
+                        paramName,
                         typeOrMethodName,
                         fr.found,
-                        fr.required);
+                        paramName + fr.required);
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3806]: Should we add a space here, between the `paramName` and the bounds?

Are the square brackets useful? How do they interact with the flag to show more details about bounds?

File: docs/CHANGELOG.md [hunk 2]
```diff
@@ -29,7 +29,7 @@ They are enabled by default and can be disabled using `-Alint=-instanceof.unsafe
 
 **Closed issues:**
 
-eisop#1247, typetools#7096.
+eisop#1247, eisop#1263, typetools#7096.
```
Comment (wmdietl) [inline docs/CHANGELOG.md:32]: Please also say something in user-visible changes.

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks!

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 1 above)
Comment (wmdietl) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3806]: I like the output that is given here: https://github.com/eisop/checker-framework/blob/ec22f85d6490bfb3a711af9157bbf0f2747c5143/framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java#L342
That is, a space after the type parameter name and spaces in the square brackets.

File: docs/CHANGELOG.md [hunk 3]
```diff
@@ -21,6 +21,7 @@ The EISOP Checker Framework now use `NullType` instead `Void` to denote the bott
 It is visible in error messages with type variable's or wildcard's lower bounds.
 The type of the `null` literal in the Nullness Checker is now displayed as `@Nullable NullType` instead of the earlier `null (NullType)`.
 This change makes the Checker Framework consistent with the Java language specification.
+The format of error messages for type variables and wildcards has been improved to be consistent when printing both bounds.
```
Comment (wmdietl) [inline docs/CHANGELOG.md:24]:
```suggestion

The format of error messages for type variables and wildcards has been improved to be consistent when printing both bounds.
```

File: checker/tests/nullness/java-unsound/Figure3.java [hunk 4]
```diff
@@ -9,9 +9,9 @@ <B> Constraint<? super B> bad() {
 
         <B> A coerce(B b) {
             // type of expression: capture#703[ extends @Initialized @Nullable Object super B[
-            // extends @Initialized @Nullable Object super @Initialized @NonNull Void]]
+            // extends @Initialized @Nullable Object super @Initialized @NonNull NullType ] ]
             // method return type: A[ extends @Initialized @Nullable Object super @Initialized
-            // @NonNull Void]
+            // @NonNull NullType ]
```
Comment (wmdietl) [inline checker/tests/nullness/java-unsound/Figure3.java:14]: Thanks for tracking these down! Can you move the NullType changes to a separate PR, after this PR is merged?

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks!

File: checker/tests/nullness/java-unsound/Figure3.java (hunk 4 above)
Comment (Ao-senXiong) [reply checker/tests/nullness/java-unsound/Figure3.java]: Reverted. I will make another PR immediately after this one so will not open a new issue.

File: framework/src/main/java/org/checkerframework/framework/type/DefaultAnnotatedTypeFormatter.java [hunk 5]
```diff
@@ -431,18 +431,18 @@ public String visitTypeVariable(
 
             if (!visiting.contains(type)) {
                 if (type.isDeclaration() && currentPrintInvisibleSetting) {
-                    sb.append("/*DECL*/ ");
+                    sb.append("/*DECL*/");
```
Comment (Ao-senXiong) [inline framework/src/main/java/org/checkerframework/framework/type/DefaultAnnotatedTypeFormatter.java:434]:
```suggestion
                    sb.append("/*DECL*/ ");
```
