### PR TITLE
Set var arg type before calling `viewpointAdaptConstructor`

### LINKED ISSUE #777: CF crashes in `ViewpointTestChecker` when calling a varargs constructor
I found out this when I run PICO against PICO itself.

Command: 
```
./checker/bin/javac -cp "framework/build/libs/framework-3.42.0-eisop4-SNAPSHOT.jar:framework/build/classes/java/main:framework/build/classes/java/test:javacutil/libs/javacutil-3.42.0-eisop4-SANPSHOT.jar:javacutil/build/classes/java/main:javacutil/build/classes/java/test" -processorpath "framework/build/classes/java/test" -processor viewpointtest.ViewpointTestChecker Test.java

```

File:
```
public class VarargType {
    void foo() {
        A a = new A("testStr", new Object());
    }
}

class A {
    A (String str, Object... args) {}
}

```

Stacktrace:
```
error: Error in AnnotatedTypeMirror.fromExpression(ViewpointTestAnnotatedTypeFactory, new BugInCF("Unknown assignment variable at:", new Object())): Set vararg type before resetting parameter types
  ; The Checker Framework crashed.  Please report the crash.  Version: Checker Framework 3.42.0-eisop4-SNAPSHOT, branch master, 2024-05-31, commit 97503e1, dirty=true. 
  Checker: class viewpointtest.ViewpointTestChecker
  Visitor: class org.checkerframework.common.basetype.BaseTypeVisitor
  Compilation unit: Test.java
  Last visited tree at line 3 column 1:
  public class Test {
  Exception: org.checkerframework.javacutil.BugInCF: Set vararg type before resetting parameter types; org.checkerframework.javacutil.BugInCF: Set vararg type before resetting parameter types
        at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedExecutableType.setParameterTypes(AnnotatedTypeMirror.java:1296)
        at org.checkerframework.framework.type.AbstractViewpointAdapter.viewpointAdaptConstructor(AbstractViewpointAdapter.java:134)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.constructorFromUse(AnnotatedTypeFactory.java:2919)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.constructorFromUse(GenericAnnotatedTypeFactory.java:1958)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitNewClass(TypeFromExpressionVisitor.java:400)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitNewClass(TypeFromExpressionVisitor.java:81)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1874)
        at jdk.compiler/com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:81)
        at org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:42)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1852)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1495)
        at org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:215)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitNode(CFAbstractTransfer.java:562)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitNode(CFAbstractTransfer.java:97)
        at org.checkerframework.dataflow.cfg.node.AbstractNodeVisitor.visitObjectCreation(AbstractNodeVisitor.java:332)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitObjectCreation(CFAbstractTransfer.java:975)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitObjectCreation(CFAbstractTransfer.java:97)
        at org.checkerframework.dataflow.cfg.node.ObjectCreationNode.accept(ObjectCreationNode.java:152)
        at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:356)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:393)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:157)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:110)
        at org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:150)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1624)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1513)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:2101)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:435)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:591)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:195)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
        at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:89)
        at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1136)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:556)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:193)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:854)
        at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1397)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1354)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
  Caused by: java.lang.Throwable
        at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:22)
        ... 44 more
  
  Underlying Exception: java.lang.Throwable; java.lang.Throwable
        at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:22)
        at org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedExecutableType.setParameterTypes(AnnotatedTypeMirror.java:1296)
        at org.checkerframework.framework.type.AbstractViewpointAdapter.viewpointAdaptConstructor(AbstractViewpointAdapter.java:134)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.constructorFromUse(AnnotatedTypeFactory.java:2919)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.constructorFromUse(GenericAnnotatedTypeFactory.java:1958)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitNewClass(TypeFromExpressionVisitor.java:400)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitNewClass(TypeFromExpressionVisitor.java:81)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1874)
        at jdk.compiler/com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:81)
        at org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:42)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1852)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1495)
        at org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:215)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitNode(CFAbstractTransfer.java:562)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitNode(CFAbstractTransfer.java:97)
        at org.checkerframework.dataflow.cfg.node.AbstractNodeVisitor.visitObjectCreation(AbstractNodeVisitor.java:332)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitObjectCreation(CFAbstractTransfer.java:975)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitObjectCreation(CFAbstractTransfer.java:97)
        at org.checkerframework.dataflow.cfg.node.ObjectCreationNode.accept(ObjectCreationNode.java:152)
        at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:356)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:393)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:157)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:110)
        at org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:150)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1624)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1513)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:2101)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:435)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:591)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:195)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
        at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:89)
        at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1136)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:556)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:193)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:854)
        at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1397)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1354)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
1 error
```

### PR DESCRIPTION
**Pull request by Ao-senXiong**
Fixes #777

### CODE REVIEW

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks!

File: framework/tests/viewpointtest/VarargType.java [hunk 1]
```diff
@@ -0,0 +1,9 @@
+public class VarargType {
+    void foo() {
+        TestClass a = new TestClass("testStr", new Object());
+    }
+}
+
+class TestClass {
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargType.java]: Done.

File: framework/tests/viewpointtest/VarargType.java [hunk 2]
```diff
@@ -0,0 +1,9 @@
+public class VarargType {
+    void foo() {
+        TestClass a = new TestClass("testStr", new Object());
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargType.java]: > Also, add tests with 1) inner classes and 2) anonymous classes.
added
>Can you add test cases that actually have some viewpoint adaptation of the constructor, including tests with expected errors?
@wmdietl do you think it is better to open a new PR for viewpoint adaptation of constructor? Because this PR is trying to fix the crash error of using vararg type.

[the remark this answers is not in the document]
Comment (wmdietl) [reply framework/tests/viewpointtest/VarargType.java]: This crash wasn't noticed because we didn't have the test case. It would be more convincing to have more test cases that actually show that constructors with varargs are now correctly adapted.

File: framework/tests/viewpointtest/VarargType.java [hunk 3]
```diff
@@ -0,0 +1,27 @@
+import viewpointtest.quals.*;
```
Comment (wmdietl) [inline framework/tests/viewpointtest/VarargType.java:1]: Can you add the usual starter text with a link to the issue that this test is for?

Comment (wmdietl) [reply framework/tests/viewpointtest/VarargType.java:1]: Tests that actually use some annotations would be nice.

File: framework/tests/viewpointtest/VarargType.java [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+
+public class VarargType {
```
Comment (wmdietl) [inline framework/tests/viewpointtest/VarargType.java:3]: What is the `Type` in the class name referring to?

File: framework/tests/viewpointtest/VarargType.java [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+
+    VarargType(String str, Object... args) {}
+
+    void foo() {
+        VarargType a = new VarargType("testStr", new Object());
+    }
+
+    // inner class
+    class Inner {
+        Inner(String str, Object... args) {}
```
Comment (wmdietl) [inline framework/tests/viewpointtest/VarargType.java:13]: How about only the varargs parameter and then test with:
- new Inner()
- new Inner(new Object())
- Varargtype.this.new Inner()
- Varargtype.this.new Inner(new Object())

To test more of the tricky combinations with inner classes.

File: framework/tests/viewpointtest/VarargType.java [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+
+        void foo() {
+            Inner a = new Inner("testStr", new Object());
+        }
+    }
+
+    // anonymous class
+    Object o =
+            new Object() {
```
Comment (wmdietl) [inline framework/tests/viewpointtest/VarargType.java:22]: This doesn't test that the varargs constructor can be used to create an anonymous class. It should be something like `new VarargType(...) { /* either nothing or some code */ }`

**Review by wmdietl — CHANGES_REQUESTED** [review]
Having one passing and one failing test with actual viewpoint adaptation would give us much more confidence that the problem is actually fixed.

File: framework/tests/viewpointtest/VarargType.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargType.java]: Okay, I will add more tests as you commented below.

File: framework/tests/viewpointtest/VarargType.java (hunk 3 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargType.java:3]: >Can you add the usual starter text with a link to the issue that this test is for?

Done

> Tests that actually use some annotations would be nice.

Done

File: framework/tests/viewpointtest/VarargType.java (hunk 4 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargType.java]: changed it to VarargsConstructor.

File: framework/tests/viewpointtest/VarargType.java (hunk 5 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargType.java]: Added.

File: framework/tests/viewpointtest/VarargType.java (hunk 6 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargType.java]: Okay, thanks!

File: framework/tests/viewpointtest/VarargsConstructor.java [hunk 7]
```diff
@@ -0,0 +1,46 @@
+// Test case for EISOP issue #777:
+// https://github.com/eisop/checker-framework/issues/777
+import viewpointtest.quals.*;
+
+public class VarargsConstructor {
+
+    VarargsConstructor(String str, Object... args) {}
+
+    @SuppressWarnings({"inconsistent.constructor.type", "super.invocation.invalid"})
```
Comment (Ao-senXiong) [inline framework/tests/viewpointtest/VarargsConstructor.java:9]: @wmdietl I feel like this is also happening when annotate the constructor in here https://github.com/eisop/checker-framework/blob/481040f5af69012d3b410e1844f31d84fff7b7c4/framework/tests/viewpointtest/PolyConstructor.java#L6. 

can you share some insight on these two error messages?

Comment (wmdietl) [reply framework/tests/viewpointtest/VarargsConstructor.java:9]: Do the full error messages not explain the errors well enough?
1.) `Constructor type (%s) is a subtype of the top type (%s), therefore it cannot be statically verified.` We cannot statically ensure that the constructor creates an object of a non-top type. Therefore, any constructor that is annotated with something non-top produces this.
2.) `Constructor of type %s cannot call %s of type %s.` The constructor from the superclass has the default annotation. The super constructor is implicitly called and this constructor has a different annotation - therefore, we get a warning about the mismatch.

Please open PRs to improve these error messages if something is unclear.

I notice that for these two errors there is no explanation in `docs/manual`.
We could improve our checks to:
1.) produce a list of all unique error keys from the `messages.properties` files.
2.) ensure each key appears somewhere in `docs/manual`. Ideally, outside of just a code example (e.g. one of the two error keys appears once as `@SuppressWarnings("super.invocation.invalid")`. Is that good enough as documentation?)
3.) ensure each key appears somewhere in the checker source code, to avoid that we have dead error messages in `messages.properties` files.
4.) ensure each key appears in at least one test case as expected error.

I'm not sure how well-covered the manual is currently for the error keys, but this looks like a nice goal to reach.
If this sounds useful, please convert this comment into an issue.

File: framework/tests/viewpointtest/VarargsConstructor.java [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+    }
+
+    void invokeConstructor(@A Object aObj, @B Object bObj, @Top Object topObj) {
+        new @A VarargsConstructor(aObj);
+        new @B VarargsConstructor(bObj);
+        new @Top VarargsConstructor(topObj);
+        // :: error: (argument.type.incompatible)
+        new @A VarargsConstructor(bObj);
+        // :: error: (argument.type.incompatible)
+        new @B VarargsConstructor(aObj);
```
Comment (wmdietl) [inline framework/tests/viewpointtest/VarargsConstructor.java:24]:
```suggestion
        @A Object a = new @A VarargsConstructor(aObj);
        @B Object b = new @B VarargsConstructor(bObj);
        @Top Object top = new @Top VarargsConstructor(topObj);
        // :: error: (argument.type.incompatible)
        new @A VarargsConstructor(bObj);
        // :: error: (argument.type.incompatible)
        new @B VarargsConstructor(aObj);
```

File: framework/tests/viewpointtest/VarargsConstructor.java [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+    }
+
+    // inner class
+    class Inner {
```
Comment (wmdietl) [inline framework/tests/viewpointtest/VarargsConstructor.java:28]:
```suggestion
    class Inner {
```

File: framework/tests/viewpointtest/VarargsConstructor.java [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+        Inner(Object... args) {}
```
Comment (wmdietl) [inline framework/tests/viewpointtest/VarargsConstructor.java:29]: Make this receiver-dependent also and test that viewpoint adaptation actually happens correctly.
In particular here, something could go wrong if the handling of the extra enclosing-this parameter isn't done correctly.

File: framework/tests/viewpointtest/VarargsConstructor.java [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+        void foo() {
+            Inner a = new Inner();
+            Inner b = new Inner(new Object());
+            Inner c = VarargsConstructor.this.new Inner();
+            Inner d = VarargsConstructor.this.new Inner(new Object());
+        }
+    }
+
+    // anonymous class
+    Object o =
```
Comment (wmdietl) [inline framework/tests/viewpointtest/VarargsConstructor.java:40]: This would also be more interesting with at least one actual viewpoint adaptation.

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks for the expansion!

File: framework/tests/viewpointtest/VarargsConstructor.java (hunk 11 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargsConstructor.java]: Updated!

File: framework/tests/viewpointtest/VarargsConstructor.java (hunk 10 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/VarargsConstructor.java]: Updated!

**Comment by Ao-senXiong** [comment]
Submitted a new issue for error key coverage #789 .

**Review by wmdietl — APPROVED** [review]
Thanks!
