### PR TITLE
Remove unused parameters, which fixes a warning suppression

### LINKED ISSUE #662: Investigate `MostSpecificVisitor`
The errorprone 2.24.0 warning suppressed in https://github.com/eisop/checker-framework/pull/661/commits/8272dcf4c57a3f9b8246cafd826a259d05ed544c looks suspicious.
Investigate that code and find a proper solution.

### PR DESCRIPTION
**Pull request by Ao-senXiong**
Fixed #662

### CODE REVIEW

**Comment by Ao-senXiong** [comment]
@wmdietl Looks like time out limit 110s is still not enough for some cases. Can you trigger the nonjunit_jdk8 to rerun?

File: framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java [hunk 1]
```diff
@@ -292,19 +290,12 @@ private class MostSpecificVisitor extends AnnotationSetCombiner {
         /**
          * Create a {@link MostSpecificVisitor}.
          *
-         * @param aTypeMirror type of the "a" value
-         * @param bTypeMirror type of the "b" value
          * @param backup value to use if no most specific value is found
          */
-        @SuppressWarnings("UnusedVariable") // TODO clean this up
-        public MostSpecificVisitor(TypeMirror aTypeMirror, TypeMirror bTypeMirror, V backup) {
+        public MostSpecificVisitor(V backup) {
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java:295]: Thanks for the cleanup!
Above, `if (ms.error) { return backup; }`, is `backup` always null if `ms.error` is true?
A few nullness annotations also seem to be missing, e.g. on `backupAMSet`.

Comment (Ao-senXiong) [reply framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java:295]: >is backup always null if ms.error is true?
I think no, the visitor will not reassign the value of `backup`. It only depends on the input.

>A few nullness annotations also seem to be missing, e.g. on backupAMSet.
I will add it.

Comment (wmdietl) [reply framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java]: > > is backup always null if ms.error is true?
> 
> I think no, the visitor will not reassign the value of `backup`. It only depends on the input.

I don't understand what you mean.
The only place where `error` is set to `true` is when `if (backupAMSet == null)`.
I think the only way that can happen is if `backup` is null.
So in

````
        if (ms.error) {
            return backup;
        }
````

I would expect that the returned value is always null.
Wouldn't the code be clearer if `null` is returned explicitly, possibly with a comment that `backup == null`?
If that argument is flawed, what am I missing?

Comment (Ao-senXiong) [reply framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java]: Thanks for clarification. See new commit [d2baafd](https://github.com/eisop/checker-framework/pull/761/commits/d2baafddf07d604b9e427be99cd0fc6d61912ab0)

File: framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java [hunk 2]
```diff
@@ -276,7 +274,8 @@ public V mostSpecific(@Nullable V other, @Nullable V backup) {
                         other.getAnnotations(),
                         canBeMissingAnnotations(mostSpecifTypeMirror));
         if (ms.error) {
-            return backup;
+            // return null because error only set to true when backup is null
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java:277]:
```suggestion
            // return null because `ms.error` is only set to true when `backup` is null.
```

**Review by wmdietl — APPROVED** [review]
Thanks!
