### PR TITLE
Fix handling of polymorphic qualifiers in conditional expressions

### LINKED ISSUE #519: PolyNull and conditional expressions
Take this code:

````java
import org.checkerframework.checker.nullness.qual.PolyNull;

class Demo {
    public static @PolyNull String toLowerCaseA(@PolyNull String text) {
        return text == null ? null : text.toLowerCase();
    }
    public static @PolyNull String toLowerCaseB(@PolyNull String text) {
        return text != null ? text.toLowerCase() : null;
    }
}
````

The two methods perform the same thing, just with flipped logic.
However, for `toLowerCaseB` we get an error:

````
Error: [conditional.type.incompatible] incompatible types in conditional expression.
   found   : null (NullType)
   required: @Initialized @NonNull String
````

### PR DESCRIPTION
**Pull request by Ao-senXiong**
Fixes #519.

### CODE REVIEW

File: checker/tests/nullness/ConditionalPolyNull.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import org.checkerframework.checker.nullness.qual.PolyNull;
+
+class ConditionalPolyNull {
+    public static @PolyNull String toLowerCaseA(@PolyNull String text) {
```
Comment (wmdietl) [inline checker/tests/nullness/ConditionalPolyNull.java:4]:
```suggestion
    @PolyNull String toLowerCaseA(@PolyNull String text) {
```

File: checker/tests/nullness/ConditionalPolyNull.java [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+        return text == null ? null : text.toLowerCase();
+    }
+
+    public static @PolyNull String toLowerCaseB(@PolyNull String text) {
```
Comment (wmdietl) [inline checker/tests/nullness/ConditionalPolyNull.java:8]:
```suggestion
    @PolyNull String toLowerCaseB(@PolyNull String text) {
```

File: checker/tests/nullness/ConditionalPolyNull.java [hunk 3]
```diff
@@ -0,0 +1,11 @@
+import org.checkerframework.checker.nullness.qual.PolyNull;
```
Comment (wmdietl) [inline checker/tests/nullness/ConditionalPolyNull.java:1]:
```suggestion
// Test case for EISOP issue #519
// https://github.com/eisop/checker-framework/issues/519
import org.checkerframework.checker.nullness.qual.PolyNull;
```

File: checker/tests/nullness/ConditionalPolyNull.java [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+
+class ConditionalPolyNull {
+    public static @PolyNull String toLowerCaseA(@PolyNull String text) {
+        return text == null ? null : text.toLowerCase();
+    }
+
+    public static @PolyNull String toLowerCaseB(@PolyNull String text) {
+        return text != null ? text.toLowerCase() : null;
```
Comment (wmdietl) [inline checker/tests/nullness/ConditionalPolyNull.java:9]: Could you add the two combinations that should raise errors, to make sure we don't break that direction?

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 5]
```diff
@@ -2343,10 +2343,12 @@ public Void visitAnnotation(AnnotationTree tree, Void p) {
      */
     @Override
     public Void visitConditionalExpression(ConditionalExpressionTree tree, Void p) {
-        AnnotatedTypeMirror cond = atypeFactory.getAnnotatedType(tree);
-        this.commonAssignmentCheck(cond, tree.getTrueExpression(), "conditional.type.incompatible");
+        AnnotatedTypeMirror condTrue = atypeFactory.getAnnotatedType(tree);
+        AnnotatedTypeMirror condFalse = atypeFactory.getAnnotatedType(tree);
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:2347]: Thanks for tracking down this problem and this fix!
I think the root cause of this issue is: https://github.com/eisop/checker-framework/blob/b7745d9fe37fde1f05525c805091d0128fdd804a/checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java#L247C62-L247C62
where the `commonAssignmentCheck` changes the type of an argument.
I think we should fix that issue - `commonAssignmentCheck` shouldn't change the type. Instead, the NullnessTransfer should properly handle `PolyNull` in the two branches.
Then here we only need one `cond` type, which will be the LUB type of the two branches. This fix works, but it is very confusing why we need to determine the type for the same tree twice. So let's look into properly fixing this.

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks for looking into this bug!

File: checker/tests/nullness/ConditionalPolyNull.java (hunk 4 above)
Comment (wmdietl) [reply checker/tests/nullness/ConditionalPolyNull.java:11]: Thanks for filing #532.
I'm not sure how you mean... in this version: `return text == null ? text.toLowerCase() : null ;` when text is non-null, the return value is null, so it the returned value violates the `@PolyNull` contract. Does that make sense?

Comment (Ao-senXiong) [reply checker/tests/nullness/ConditionalPolyNull.java:11]: Thanks for the explanation. Yes, this makes sense. Then how to understand the error message below?
```
found : @FBCBottom @PolyNull String
required : @Initialized @NonNull String
```
The required type is `@NonNull` make sense. Why the found type is `@PolyNull` for return value 'null'?

Comment (wmdietl) [reply checker/tests/nullness/ConditionalPolyNull.java:11]: I think you're talking about this error message:

````
checker/tests/nullness/ConditionalPolyNull.java:21: error: [method.invocation.invalid] call to toLowerCase() not allowed on the given receiver.
        return text != null ? null : text.toLowerCase();
                                                     ^
  found   : @FBCBottom @PolyNull String
  required: @Initialized @NonNull String
````

For which you already filed the separate issue #532.
Is that the error you mean? If so, we should discuss in #532. If not, please clarify which error you're talking about.

Comment (Ao-senXiong) [reply checker/tests/nullness/ConditionalPolyNull.java:11]: Sorry, I miscopied the wrong error message. This is the error I am referencing: 
```
checker/tests/nullness/ConditionalPolyNull.java:16: error: [return.type.incompatible] incompatible types in return.
        return text == null ? text.toLowerCase() : null ;
                            ^
  type of expression: @Initialized @Nullable String
  method return type: @Initialized @PolyNull String
```
If `text == null` condition is false, the `@PolyNull` of both method return type and argument type will be conservatively replaced with `@NonNull` by data flow refinement. However, the method return type is still `@PolyNull` here. 

Should the `@PolyNull` be replaced by `@NonNull` here?

Comment (wmdietl) [reply checker/tests/nullness/ConditionalPolyNull.java:11]: But after replacing `@PolyNull` with `@NonNull` in the return type, you would still get a mismatch - the returned expression is `@Nullable`.
Let's try to fix the type changes in `commonAssignmentCheck` and move them to somewhere more appropriate. Then we can see whether the types make sense or not.

Comment (Ao-senXiong) [reply checker/tests/nullness/ConditionalPolyNull.java:11]: Yes, you are right. :)

Comment (Ao-senXiong) [reply checker/tests/nullness/ConditionalPolyNull.java:11]: I believe these two are actually  related #540, because when I add `@PolyNull` to https://github.com/eisop/checker-framework/blob/d1d2d48f68f3da081df82d6edfa0f200e19cb319/checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java#L688C101-L688C101, the odd error `method.invocation.invalid` is gone.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 5 above)
Comment (Ao-senXiong) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:2347]: @wmdietl A question here, if we are planning to use the LUB type of the two branches here, I think we are going to have a false positive in this example:
```
    @PolyNull String toLowerCaseA(@PolyNull String text) {
        return text == null ? null : text.toLowerCase();
    }
```
The LUB type would be `@Nullable`. And we check ` text.toLowerCase()`, there would be a dereference.of.nullable error. (At least I do not want this error message).

File: checker/tests/nullness/ConditionalPolyNull.java (hunk 4 above)
Comment (wmdietl) [reply checker/tests/nullness/ConditionalPolyNull.java:11]: Yes, that's why we split of #540 from this issue.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 5 above)
Comment (wmdietl) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:2347]: The type of the conditional expression, that is, the type for the whole expression `text == null ? null : text.toLowerCase()`, should be `@PolyNull String`.
The type in the true and false branch can still have refinements. In the then branch we know `text` is null and in the else branch we know `text` is non-null. So no dereference error should be raised.

Comment (Ao-senXiong) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:2347]: Get it. Thanks.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 6]
```diff
@@ -2340,13 +2340,18 @@ public Void visitAnnotation(AnnotationTree tree, Void p) {
...
      * another failsafe guard and do the checks.
+     *
+     * <p>Note we pass a copy of condThen as an argument for the second invocation of
+     * commonAssignmentCheck because the method has side effect.
      */
     @Override
     public Void visitConditionalExpression(ConditionalExpressionTree tree, Void p) {
-        AnnotatedTypeMirror cond = atypeFactory.getAnnotatedType(tree);
-        this.commonAssignmentCheck(cond, tree.getTrueExpression(), "conditional.type.incompatible");
+        AnnotatedTypeMirror condThen = atypeFactory.getAnnotatedType(tree);
```
Comment (Ao-senXiong) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:2349]: PolyRegx same problem?
Also basetype visitor or nullness visitor?

Comment (Ao-senXiong) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:2349]: document what proper fix would be

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 7]
```diff
@@ -793,10 +793,25 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
         return super.visitDoWhileLoop(tree, p);
     }
 
+    /**
+     * Note: we pass a copy of condThen as an argument for the second invocation of
+     * commonAssignmentCheck because the method has side effect. A better way is remove
+     * replacePolyQualifier in common assignmentCheck and handle two conditional branches properly
+     * in Nullness transfer.
```
Comment (Ao-senXiong) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:800]:
```suggestion
     * in NullnessTransfer.
```

File: checker/tests/nullness/ReplacePolyNull.java [hunk 8]
```diff
@@ -0,0 +1,19 @@
+import org.checkerframework.checker.nullness.qual.PolyNull;
+
+public class ReplacePolyNull {
+
+    @PolyNull String foo(@PolyNull String param) {
+        if (param != null) {
+            //  @PolyNull is really @Nullable, so change
+            // the type of param to @Nullable.
+            return param;
```
Comment (wmdietl) [inline checker/tests/nullness/ReplacePolyNull.java:9]:
```suggestion
            return param.toString();
```

To illustrate that `param` is `@NonNull` here.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 9]
```diff
@@ -793,10 +793,25 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
         return super.visitDoWhileLoop(tree, p);
     }
 
+    /**
+     * Note: we pass a copy of condThen as an argument for the second invocation of
+     * commonAssignmentCheck because the method has side effect. A better way is remove
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:798]: Thanks, done.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 10]
```diff
@@ -793,10 +793,25 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
         return super.visitDoWhileLoop(tree, p);
     }
 
+    /**
+     * Note: we pass a copy of condThen as an argument for the second invocation of
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:797]: Ok, thanks for the advice.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 11]
```diff
@@ -793,10 +793,25 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
...
+     * commonAssignmentCheck because the method has side effect. A better way is remove
+     * replacePolyQualifier in common assignmentCheck and handle two conditional branches properly
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:799]: Finished rewording, also add a TODO comment on `commonAssignmentCheck`

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 12]
```diff
@@ -793,10 +793,25 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
...
+     * in NullnessTransfer.
+     */
     @Override
     public Void visitConditionalExpression(ConditionalExpressionTree tree, Void p) {
         checkForNullability(tree.getCondition(), CONDITION_NULLABLE);
-        return super.visitConditionalExpression(tree, p);
+        AnnotatedTypeMirror condThen = atypeFactory.getAnnotatedType(tree);
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:805]: Done.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 13]
```diff
@@ -793,10 +793,25 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
...
+        AnnotatedTypeMirror condElse = condThen.deepCopy();
+        this.commonAssignmentCheck(
+                condThen, tree.getTrueExpression(), "conditional.type.incompatible");
+        this.commonAssignmentCheck(
+                condElse, tree.getFalseExpression(), "conditional.type.incompatible");
+        Void r = scan(tree.getCondition(), p);
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:811]: Done.

File: checker/tests/nullness/ReplacePolyNull.java [hunk 14]
```diff
@@ -0,0 +1,19 @@
+import org.checkerframework.checker.nullness.qual.PolyNull;
+
+public class ReplacePolyNull {
+
+    @PolyNull String foo(@PolyNull String param) {
+        if (param != null) {
+            //  @PolyNull is really @Nullable, so change
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply checker/tests/nullness/ReplacePolyNull.java:7]: Sorry, i made a mistake. Corrected now.

File: checker/tests/nullness/ReplacePolyNull.java [hunk 15]
```diff
@@ -0,0 +1,19 @@
+import org.checkerframework.checker.nullness.qual.PolyNull;
+
+public class ReplacePolyNull {
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply checker/tests/nullness/ReplacePolyNull.java:3]: Ok, I will merge the tests in here.

File: checker/tests/nullness/ReplacePolyNull.java (hunk 8 above)
Comment (Ao-senXiong) [reply checker/tests/nullness/ReplacePolyNull.java:9]: Thanks for the advise, done.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 16]
```diff
@@ -245,6 +245,7 @@ protected void commonAssignmentCheck(
         // Use the valueExp as the context because data flow will have a value for that tree.  It
         // might not have a value for the var tree.  This is sound because if data flow has
         // determined @PolyNull is @Nullable at the RHS, then it is also @Nullable for the LHS.
+        // TODO: Hack here, remove replacePolyQualifier as referred in visitConditionalExpression.
```
Comment (Ao-senXiong) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:248]: I leave this to a TODO task and try to keep the words in just one sentence:)

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 17]
```diff
@@ -795,8 +796,26 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
 
     @Override
     public Void visitConditionalExpression(ConditionalExpressionTree tree, Void p) {
+        // Note: A copy of condThen is provided as an argument to the second invocation of
+        // NullnessVisitor#commonAssignmentCheck. This approach is taken due to the method's side
+        // effects now.
+        // A more appropriate handling of the conditional expression would involve removing
+        // replacePolyQualifier from commonAssignmentCheck, and then managing the two branches
+        // separately within Nullnesstransfer.
```
Comment (Ao-senXiong) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:804]: move the comment down

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 18]
```diff
@@ -795,8 +796,26 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
...
         checkForNullability(tree.getCondition(), CONDITION_NULLABLE);
-        return super.visitConditionalExpression(tree, p);
+        // This check's logic should be kept in same with the super method in the future.
+        AnnotatedTypeMirror condThen = atypeFactory.getAnnotatedType(tree);
+        AnnotatedTypeMirror condElse = condThen.deepCopy();
+        this.commonAssignmentCheck(
+                condThen, tree.getTrueExpression(), "conditional.type.incompatible");
+        this.commonAssignmentCheck(
+                condElse, tree.getFalseExpression(), "conditional.type.incompatible");
+        // Avoid calling super, as it will trigger an incorrect warning. Instead, manually implement
```
Comment (Ao-senXiong) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:813]: incorrect warning wrong

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java [hunk 19]
```diff
@@ -795,8 +796,26 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
...
+        // the logic from TreeScanner#visitConditionalExpression to finalize the check.
```
Comment (Ao-senXiong) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessVisitor.java:814]: subtree != finalize check

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java [hunk 20]
```diff
@@ -259,6 +259,9 @@ protected void commonAssignmentCheck(
         // Use the valueExp as the context because data flow will have a value for that tree.  It
         // might not have a value for the var tree.  This is sound because if data flow has
         // determined @PolyNull is @Nullable at the RHS, then it is also @Nullable for the LHS.
+        // TODO: replacePolyQualifier is a temporary hack as it produce side effect to polymorphic
```
Comment (wmdietl) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:262]: How about: `A visitor should not change types, so this call to replacePolyQualifier is a hack. To work around this hack here, NullnessVisitor#visitConditionalExpression needs a further hack. Both should be undone, by properly resolving polymorphic qualifiers in the ATF/transfer.`

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java [hunk 21]
```diff
@@ -811,7 +814,26 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
     @Override
     public Void visitConditionalExpression(ConditionalExpressionTree tree, Void p) {
         checkForNullability(tree.getCondition(), CONDITION_NULLABLE);
-        return super.visitConditionalExpression(tree, p);
+        // Note: A copy of condThen is provided as an argument to the second invocation of
```
Comment (wmdietl) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:817]: How about: `Because of the hack in NullnessVisitor#commonAssignmentCheck, this code needs to use a copy of the types for the two invocations of #commonAssignmentCheck. These hacks should be undone, by properly resolving polymorphic qualifiers in the ATF/transfer.
As this code is mostly duplicated from the super method, this code needs to be kept in sync.`

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java [hunk 22]
```diff
@@ -811,7 +814,26 @@ public Void visitDoWhileLoop(DoWhileLoopTree tree, Void p) {
...
+        // replacePolyQualifier from commonAssignmentCheck, and then managing the two branches
+        // separately within Nullnesstransfer.
+        // This check's logic should be kept in sync with the super method.
+        AnnotatedTypeMirror condThen = atypeFactory.getAnnotatedType(tree);
+        AnnotatedTypeMirror condElse = condThen.deepCopy();
+        this.commonAssignmentCheck(
+                condThen, tree.getTrueExpression(), "conditional.type.incompatible");
+        this.commonAssignmentCheck(
+                condElse, tree.getFalseExpression(), "conditional.type.incompatible");
+        // Avoid calling super, as it will trigger a false negative in the false branch of super
```
Comment (wmdietl) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:830]: `trigger a false negative` sounds odd, as for a false negative nothing happens. What did you mean?

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks, looks good, just comment suggestions.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java (hunk 22 above)
Comment (Ao-senXiong) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:830]: I will try to say the super method does not handle conditional branches correctly and we use a hack here.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java (hunk 20 above)
Comment (Ao-senXiong) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:262]: Cool, thanks. I definitely should try to express more clearly.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java (hunk 22 above)
Comment (wmdietl) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java]: I don't think anything was wrong with the super method... if so, we should fix it there or at least also add a comment there.

Comment (Ao-senXiong) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java]: how about `Avoid calling super, as the current method uses a hack and does not sync with the super method. Instead, manually implement the logic from TreeScanner#visitConditionalExpression to traverse the subtree.`

**Review by wmdietl — APPROVED** [review]
Thanks, looks good now!
