### PR TITLE
Finds better position for reporting issues on artificial trees

### LINKED ISSUE #244: Errors for inferred type arguments of lambda parameters have no location
```java
class Lib<T extends Object> {}

@SuppressWarnings("nullness")
interface LibConsumer<T> {
  void consume(Lib<T> a);
}

class User<T> {
  LibConsumer<T> f = t -> {};
}
```

```
$ $HOME/checker-framework-3.22.0-eisop1/checker/bin/javac -processor nullness NoLocation.java
error: [type.argument.type.incompatible] incompatible type argument for type parameter T of Lib.
  found   : T extends @Initialized @Nullable Object
  required: @Initialized @NonNull Object
1 error
```

In contrast, if I change the line inside `User` to...

```java
LibConsumer<T> f = (Lib<T> t) -> {};
```

..._then_ I get a filename and line number:

```
NoLocation.java:9: error: [type.argument.type.incompatible] incompatible type argument for type parameter T of Lib.
  LibConsumer<T> f = (Lib<T> t) -> {};
                          ^
  found   : T extends @Initialized @Nullable Object
  required: @Initialized @NonNull Object
1 error
```

This issue also exists in typetools. It has caused periodic confusion. I'm finally getting around to filing an issue because I got extra confused this time when the error about `Lib` appeared in a file that didn't even contain the word `Lib` :)

### PR DESCRIPTION
**Pull request by zcai1**
This PR aims to fix issue #244. To report issues on an artificial tree, we use the innermost non-artificial parent to provide the position.

Fixes #244

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java [hunk 1]
```diff
@@ -2104,7 +2171,7 @@ public boolean shouldSuppressWarnings(Tree tree, String errKey) {
         }
 
         // trees.getPath might be slow, but this is only used in error reporting
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java:2173]: This comment can be removed or adapted now?

File: framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java [hunk 2]
```diff
@@ -2104,7 +2171,7 @@ public boolean shouldSuppressWarnings(Tree tree, String errKey) {
...
-        @Nullable TreePath path = trees.getPath(this.currentRoot, tree);
+        @Nullable TreePath path = getTreePathCacher().getPath(currentRoot, tree);
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java:2174]: At the very bottom of this file is method `getPathToCompilationUnit`. Could it's implementation also benefit from using the `TreePathCacher`?

**Review by wmdietl — COMMENTED** [review]
Thanks for this improvement, very nicely solved!
I just have two small comments.
Can you also add something to the changelog?

File: framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java (hunk 1 above)
Comment (zcai1) [reply framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java]: Yes, I have removed the comment since it seems having a treepath is necessary for the logic.

File: framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java (hunk 2 above)
Comment (zcai1) [reply framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java:2172]: Thanks for the reminder! Yes, I have updated the method.

**Review by wmdietl — APPROVED** [review]
Thanks!
