### PR TITLE
Set the the current class as the receiver of `this` constructor calls

### LINKED ISSUE #782: Receiver of `this()` call is null
Command: 
```
./checker/bin/javac -cp "framework/build/libs/framework-3.42.0-eisop4-SNAPSHOT.jar:framework/build/classes/java/main:framework/build/classes/java/test:javacutil/libs/javacutil-3.42.0-eisop4-SANPSHOT.jar:javacutil/build/classes/java/main:javacutil/build/classes/java/test" -processorpath "framework/build/classes/java/test" -processor viewpointtest.ViewpointTestChecker Test.java

```
UPDATED:
File:
```
public class Test {
    public Test () {
    }
    public Test(String str) {
        this();
    }
}

```

Stacktrace:
```
error: Error in AnnotatedTypeMirror.fromExpression(ViewpointTestAnnotatedTypeFactory, this()): null
  ; The Checker Framework crashed.  Please report the crash.  Version: Checker Framework 3.42.0-eisop4-SNAPSHOT, branch master, 2024-06-05, commit 481040f, dirty=true. 
  Checker: class viewpointtest.ViewpointTestChecker
  Visitor: class org.checkerframework.common.basetype.BaseTypeVisitor
  Compilation unit: Test.java
  Last visited tree at line 1 column 1:
  public class Test {
  Exception: java.lang.AssertionError; java.lang.AssertionError
        at org.checkerframework.framework.type.AbstractViewpointAdapter.combineTypeWithType(AbstractViewpointAdapter.java:231)
        at org.checkerframework.framework.type.AbstractViewpointAdapter.viewpointAdaptMethod(AbstractViewpointAdapter.java:171)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:2570)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:2512)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:2299)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:413)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:81)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1813)
        at jdk.compiler/com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:81)
        at org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:42)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1852)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1495)
        at org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:215)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:999)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:97)
        at org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:124)
        at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:356)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:393)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:157)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:110)
        at org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:150)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1624)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.performFlowAnalysis(GenericAnnotatedTypeFactory.java:1513)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.checkAndPerformFlowAnalysis(GenericAnnotatedTypeFactory.java:2101)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.preProcessClassTree(GenericAnnotatedTypeFactory.java:435)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:591)
        at org.checkerframework.common.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:195)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
        at org.checkerframework.framework.source.SourceVisitor.visit(SourceVisitor.java:89)
        at org.checkerframework.framework.source.SourceChecker.typeProcess(SourceChecker.java:1136)
        at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess(BaseTypeChecker.java:556)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:193)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:854)
        at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1397)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1354)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
1 error

```

### PR DESCRIPTION
**Pull request by Ao-senXiong**
Fixes #782

### CODE REVIEW

File: framework/tests/viewpointtest/ReceiverTypeNonNullTest.java [hunk 1]
```diff
@@ -0,0 +1,17 @@
+// Test case for EISOP issue #782:
+// https://github.com/eisop/checker-framework/issues/782
+public class ReceiverTypeNonNullTest {
+    public ReceiverTypeNonNullTest() {}
+
+    public ReceiverTypeNonNullTest(Object... objs) {
```
Comment (wmdietl) [inline framework/tests/viewpointtest/ReceiverTypeNonNullTest.java:6]: The original test case in #782 didn't use varargs. Is this needed to reproduce the problem?
If not, it would be nicer to actually test that the modified code path is executed - that is, add test cases that adapt the super constructor relative to the type of the current constructor and ensure that types match up. And again a test that shows that expected errors are raised.

File: framework/tests/viewpointtest/ReceiverTypeNonNullTest.java [hunk 2]
```diff
@@ -0,0 +1,17 @@
+// Test case for EISOP issue #782:
+// https://github.com/eisop/checker-framework/issues/782
+public class ReceiverTypeNonNullTest {
```
Comment (wmdietl) [inline framework/tests/viewpointtest/ReceiverTypeNonNullTest.java:3]: How about two tests: `SuperConstructorCalls` and `ThisConstructorCalls` and have a few tests that ensure the corresponding constructor calls are correctly adapted?

**Review by wmdietl — CHANGES_REQUESTED** [review]
Change itself looks good, but better test coverage would be nice.

File: framework/tests/viewpointtest/ThisConstructorCalls.java [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+    public @ReceiverDependentQual ThisConstructorCalls(@ReceiverDependentQual Object str) {}
+
+    @SuppressWarnings({"inconsistent.constructor.type", "super.invocation.invalid"})
+    public @A ThisConstructorCalls(@A float number) {}
+
+    public ThisConstructorCalls(String str) {
+        this();
+    }
+
+    public ThisConstructorCalls(String str, @A Object obj) {
```
Comment (Ao-senXiong) [inline framework/tests/viewpointtest/ThisConstructorCalls.java:18]: Add return type of constructor test. `@A` ThisConstructorCalls

File: framework/tests/viewpointtest/SuperConstructorCalls.java [hunk 4]
```diff
@@ -0,0 +1,48 @@
+// Test case for EISOP issue #782:
+// https://github.com/eisop/checker-framework/issues/782
+import viewpointtest.quals.*;
+
+public class SuperConstructorCalls extends superClass {
+    public SuperConstructorCalls() {}
```
Comment (Ao-senXiong) [inline framework/tests/viewpointtest/SuperConstructorCalls.java:6]: name class properly

File: framework/tests/viewpointtest/ReceiverTypeNonNullTest.java (hunk 2 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/ReceiverTypeNonNullTest.java]: Added in the new commits.

File: framework/tests/viewpointtest/ReceiverTypeNonNullTest.java (hunk 1 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/ReceiverTypeNonNullTest.java]: Removed varargs now. Please see latest test cases.

File: framework/tests/viewpointtest/SuperConstructorCalls.java [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+
+        public Inner(Object obj) {
+            super();
+        }
+
+        public Inner(int number, @Top Object obj) {
+            super(obj);
+        }
+
+        // :: warning: (inconsistent.constructor.type)
```
Comment (wmdietl) [inline framework/tests/viewpointtest/SuperConstructorCalls.java:26]: When do you expect a warning and when do you use a `@SuppressWarnings`?
The warning here is for the same reason as above, where you used `@SuppressWarnings`, so for consistency it would be good to use the same style.

File: framework/tests/viewpointtest/SuperConstructorCalls.java [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+        public @A Inner(int number, @A Object obj1, @B Object obj2) {
+            super(obj1);
+        }
+
+        // :: warning: (inconsistent.constructor.type)
+        public @B Inner(int number, @B Object obj1, @A Object obj2, @Top Object obj3) {
```
Comment (wmdietl) [inline framework/tests/viewpointtest/SuperConstructorCalls.java:32]: It would be good if you used the parameters more consistently - e.g. the first parameter is the one you actually use and the ones that are there only for overloading should make that clearer, e.g. by being named `dummy`.
This one is particularly confusing, as the meaning for `obj1` changes to the ones before.

File: framework/tests/viewpointtest/SuperConstructorCalls.java [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+            super(obj1);
```
Comment (wmdietl) [inline framework/tests/viewpointtest/SuperConstructorCalls.java:33]: It would be nice to have at least one failing test that actually needs viewpoint adaptation.
Tests below have no RDQ, so viewpoint adaptation is boring. Also, they only test for incompatible arguments, not that the constructed object is actually what you want, e.g. have the right argument, but the constructed object from `super` is not what the current constructor expects.

File: framework/tests/viewpointtest/ThisConstructorCalls.java [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+        this(obj);
+    }
+
+    // :: warning: (inconsistent.constructor.type)
+    public @A ThisConstructorCalls(Boolean bool, @B Object obj) {
+        // :: error: (argument.type.incompatible)
+        this(obj);
```
Comment (wmdietl) [inline framework/tests/viewpointtest/ThisConstructorCalls.java:25]: Same comments as for `super` above.

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks for expanding the tests!

File: framework/tests/viewpointtest/SuperConstructorCalls.java (hunk 6 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/SuperConstructorCalls.java]: Thanks, I have updated the argument list and naming.

File: framework/tests/viewpointtest/SuperConstructorCalls.java (hunk 7 above)
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/SuperConstructorCalls.java]: Thanks, I have expanded the test cases.

**Review by wmdietl — APPROVED** [review]
Just one follow-up comment.

File: framework/tests/viewpointtest/SuperConstructorCalls.java [hunk 9]
```diff
@@ -0,0 +1,41 @@
+// Test case for EISOP issue #782:
+// https://github.com/eisop/checker-framework/issues/782
+import viewpointtest.quals.*;
+
+public class SuperConstructorCalls {
+
+    public SuperConstructorCalls() {}
+
+    public SuperConstructorCalls(@ReceiverDependentQual Object obj) {}
```
[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/SuperConstructorCalls.java:9]: @wmdietl Can you say more about why `Top always better than RDQ if the constructor result isn't also RDQ?`? Why does argument type and return type have to be top at the same time?

[the remark this answers is not in the document]
Comment (wmdietl) [reply framework/tests/viewpointtest/SuperConstructorCalls.java:9]: Can you write an example where the constructor is Top and the parameter is RDQ and you can do something that you can't do if both are Top?

[the remark this answers is not in the document]
Comment (wmdietl) [reply framework/tests/viewpointtest/SuperConstructorCalls.java:9]: Try to do the same with the receiver type of a method, a parameter type, and the return type. Should there be a similar restriction?

[the remark this answers is not in the document]
Comment (Ao-senXiong) [reply framework/tests/viewpointtest/SuperConstructorCalls.java:9]: @wmdietl Got it, thanks! Filed a new issue #870 and we can merge this one.

**Comment by Ao-senXiong** [comment]
@wmdietl Should we merge this PR?

**Review by wmdietl — APPROVED** [review]
Thanks!
Can you prepare a separate PR that updates the changelog with the fixed issues of the past few PRs.
