### PR TITLE
Consider the GenericAnnotatedTypeFactory annotated, but ignore errors

### LINKED ISSUE #1536: CI started failing with Ubuntu 24.04 runner image update
CI for master and PRs started failing around Feb. 13th. The new failure is in typecheck-part2:

````
> Task :framework:checkCompilerMessages
> Task :framework:checkNullness
/home/runner/work/checker-framework/checker-framework/framework/src/main/java/org/checkerframework/framework/type/SubtypeIsSubsetQualifierHierarchy.java:43: error: [keyfor:argument.type.incompatible] incompatible argument for parameter atypeFactory of MostlyNoElementQualifierHierarchy constructor.
        super(qualifierClasses, processingEnv.getElementUtils(), atypeFactory);
                                                                 ^
  found   : @UnknownKeyFor GenericAnnotatedTypeFactory<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015 [ extends @UnknownKeyFor CFAbstractStore<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015> super @KeyForBottom NullType ], capture#01016 [ extends @UnknownKeyFor CFAbstractTransfer<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015 [ extends @UnknownKeyFor CFAbstractStore<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015> super @KeyForBottom NullType ], capture#01016> super @KeyForBottom NullType ], capture#01017 [ extends @UnknownKeyFor CFAbstractAnalysis<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015 [ extends @UnknownKeyFor CFAbstractStore<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015> super @KeyForBottom NullType ], capture#01016 [ extends @UnknownKeyFor CFAbstractTransfer<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015 [ extends @UnknownKeyFor CFAbstractStore<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015> super @KeyForBottom NullType ], capture#01016> super @KeyForBottom NullType ]> super @KeyForBottom NullType ]>
  required: @UnknownKeyFor GenericAnnotatedTypeFactory<? [ extends @UnknownKeyFor Object super @UnknownKeyFor NullType ], ? [ extends @UnknownKeyFor Object super @UnknownKeyFor NullType ], ? [ extends @UnknownKeyFor Object super @UnknownKeyFor NullType ], ? [ extends @UnknownKeyFor Object super @KeyForBottom NullType ]>
/home/runner/work/checker-framework/checker-framework/framework/src/main/java/org/checkerframework/framework/type/SubtypeIsSubsetQualifierHierarchy.java:43: error: [nullness:argument.type.incompatible] incompatible argument for parameter atypeFactory of MostlyNoElementQualifierHierarchy constructor.
        super(qualifierClasses, processingEnv.getElementUtils(), atypeFactory);
                                                                 ^
  found   : @NonNull GenericAnnotatedTypeFactory<capture#01014 extends @Nullable CFAbstractValue<capture#01014>, capture#01015 extends @Nullable CFAbstractStore<capture#01014 extends @Nullable CFAbstractValue<capture#01014>, capture#01015>, capture#01016 extends @Nullable CFAbstractTransfer<capture#01014 extends @Nullable CFAbstractValue<capture#01014>, capture#01015 extends @Nullable CFAbstractStore<capture#01014 extends @Nullable CFAbstractValue<capture#01014>, capture#01015>, capture#01016>, capture#01017 extends @Nullable CFAbstractAnalysis<capture#01014 extends @Nullable CFAbstractValue<capture#01014>, capture#01015 extends @Nullable CFAbstractStore<capture#01014 extends @Nullable CFAbstractValue<capture#01014>, capture#01015>, capture#01016 extends @Nullable CFAbstractTransfer<capture#01014 extends @Nullable CFAbstractValue<capture#01014>, capture#01015 extends @Nullable CFAbstractStore<capture#01014 extends @Nullable CFAbstractValue<capture#01014>, capture#01015>, capture#01016>>>
  required: @NonNull GenericAnnotatedTypeFactory<? extends @NonNull Object, ? extends @NonNull Object, ? extends @NonNull Object, ? extends @Nullable Object>
/home/runner/work/checker-framework/checker-framework/framework/src/main/java/org/checkerframework/framework/type/SubtypeIsSubsetQualifierHierarchy.java:43: error: [nullness:argument.type.incompatible] incompatible argument for parameter atypeFactory of MostlyNoElementQualifierHierarchy constructor.
        super(qualifierClasses, processingEnv.getElementUtils(), atypeFactory);
                                                                 ^
  found   : @Initialized GenericAnnotatedTypeFactory<capture#01014 extends @UnknownInitialization CFAbstractValue<capture#01014>, capture#01015 extends @UnknownInitialization CFAbstractStore<capture#01014 extends @UnknownInitialization CFAbstractValue<capture#01014>, capture#01015>, capture#01016 extends @UnknownInitialization CFAbstractTransfer<capture#01014 extends @UnknownInitialization CFAbstractValue<capture#01014>, capture#01015 extends @UnknownInitialization CFAbstractStore<capture#01014 extends @UnknownInitialization CFAbstractValue<capture#01014>, capture#01015>, capture#01016>, capture#01017 extends @UnknownInitialization CFAbstractAnalysis<capture#01014 extends @UnknownInitialization CFAbstractValue<capture#01014>, capture#01015 extends @UnknownInitialization CFAbstractStore<capture#01014 extends @UnknownInitialization CFAbstractValue<capture#01014>, capture#01015>, capture#01016 extends @UnknownInitialization CFAbstractTransfer<capture#01014 extends @UnknownInitialization CFAbstractValue<capture#01014>, capture#01015 extends @UnknownInitialization CFAbstractStore<capture#01014 extends @UnknownInitialization CFAbstractValue<capture#01014>, capture#01015>, capture#01016>>>
  required: @Initialized GenericAnnotatedTypeFactory<? extends @Initialized Object, ? extends @Initialized Object, ? extends @Initialized Object, ? extends @UnknownInitialization Object>
3 errors

FAILURE: Build failed with an exception.

> Task :framework:checkNullness FAILED

gradle/actions: Writing build results to /home/runner/work/_temp/.gradle-actions/build-results/__run_2-1771177828773.json

[Incubating] Problems report is available at: file:///home/runner/work/checker-framework/checker-framework/build/reports/problems/problems-report.html
46 actionable tasks: 35 executed, 9 from cache, 2 up-to-date
* What went wrong:
Execution failed for task ':framework:checkNullness'.
> Compilation failed; see the compiler output below.
  /home/runner/work/checker-framework/checker-framework/framework/src/main/java/org/checkerframework/framework/type/SubtypeIsSubsetQualifierHierarchy.java:43: error: [keyfor:argument.type.incompatible] incompatible argument for parameter atypeFactory of MostlyNoElementQualifierHierarchy constructor.
          super(qualifierClasses, processingEnv.getElementUtils(), atypeFactory);
                                                                   ^
    found   : @UnknownKeyFor GenericAnnotatedTypeFactory<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015 [ extends @UnknownKeyFor CFAbstractStore<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015> super @KeyForBottom NullType ], capture#01016 [ extends @UnknownKeyFor CFAbstractTransfer<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015 [ extends @UnknownKeyFor CFAbstractStore<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015> super @KeyForBottom NullType ], capture#01016> super @KeyForBottom NullType ], capture#01017 [ extends @UnknownKeyFor CFAbstractAnalysis<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015 [ extends @UnknownKeyFor CFAbstractStore<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015> super @KeyForBottom NullType ], capture#01016 [ extends @UnknownKeyFor CFAbstractTransfer<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015 [ extends @UnknownKeyFor CFAbstractStore<capture#01014 [ extends @UnknownKeyFor CFAbstractValue<capture#01014> super @KeyForBottom NullType ], capture#01015> super @KeyForBottom NullType ], capture#01016> super @KeyForBottom NullType ]> super @KeyForBottom NullType ]>
    required: @UnknownKeyFor GenericAnnotatedTypeFactory<? [ extends @UnknownKeyFor Object super @UnknownKeyFor NullType ], ? [ extends @UnknownKeyFor Object super @UnknownKeyFor NullType ], ? [ extends @UnknownKeyFor Object super @UnknownKeyFor NullType ], ? [ extends @UnknownKeyFor Object super @KeyForBottom NullType ]>
  3 errors

* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights.

BUILD FAILED in 8m 51s
````

The failure continues to happen in CI, but I fail to reproduce it locally.

The only change in CI is the automatic update of the Ubuntu runner image from:
- https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20260201.15 to
- https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20260209.23

They seem to be using the same JDK build, so I do not understand what other package change could cause the failure.
Nothing in the diff jumps out at me: https://github.com/actions/runner-images/compare/ubuntu24/20260209.23...ubuntu24/20260201.15

Even more interestingly, https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20260209.31 was updated at the same point as the Ubuntu 24.04 runner.
Downgrading to use Ubuntu 22.04 https://github.com/eisop/checker-framework/pull/1535 seems to fix the errors.

I'll merge #1535 if all CI tests pass, but it would be good to figure out what in the Ubuntu 24.04 update broke things.

### PR DESCRIPTION
**Pull request by wmdietl**
There are over 600 errors, so too much to annotate at the moment.
But the hope is that considering the GATF annotated will fix #1536.

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/type/QualifierHierarchy.java [hunk 1]
```diff
@@ -218,7 +218,6 @@ public final boolean isSubtypeQualifiersOnly(
      * @return true iff {@code subQualifier} is a subqualifier of, or equal to, {@code
      *     superQualifier}
      */
-    @SuppressWarnings({"nullness", "keyfor"}) // AnnotatedTypeFactory hasn't been annotated.
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/QualifierHierarchy.java]: We run the type check tasks with `-AwarnUnneededSuppressions`, but there was no warning about this suppression. Type checkings seems to pass without it, though.
