### PR TITLE
Fix DefaultForTypeAnnotator to deal with annotated types

### LINKED ISSUE #333: DefaultFor only applies to unannotated types
In the attached example, `@MyFenum` is supposed to be the `@DefaultFor(types={int.class})`. However, this default only applies to the bare `int` in line 8, not to the annotated `@NonNegative int` in line 10! Run the example with `path/to/javac -classpath qual:test -processor fenum -Aquals=MyFenum test/Test.java `

This is the case because @DefaultFor does not consider that `annotatedTypeMirror.getUnderlyingType()` may contain annotations; in our example, it only sees that  `@NonNegative int` is not equal to `int`, and thus does not apply the default. I originally thought that the underlying type should not contain annotations in the first place, but in fact annotations explicitly specified in the code are intentionally saved in the underlying type instead of directly in the annotated type mirror; these are accessible by `atm.getExplicitAnnotations()`. Thus, the correct fix is to change `DefaultForTypeAnnotator` to deal with annotated types.

[Checker Framework bug.tar.gz](https://github.com/eisop/checker-framework/files/9561229/Checker.Framework.bug.tar.gz)

### PR DESCRIPTION
**Pull request by flo2702**
Fixes #333 by allowing `DefaultForTypeAnnotator` to deal with annotated types. E.g., the `@DefaultFor(types={int.class})` will now not only be applied to unannotated `int`s, but also to `@NonNegative int`s etc.

### CODE REVIEW

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks for this fix!

File: docs/examples/fenum-extension/FenumDemo.java [hunk 1]
```diff
@@ -43,6 +52,11 @@ void foo() {
         myFenumArg(TestStatic.CCONST1); // ok
     }
 
+    @DefaultQualifier(MyFenum.class)
+    void bar() {
+        int int0 = TestStatic.CCONST1; // ok, @MyFenum applies by default in this method
```
Comment (wmdietl) [inline docs/examples/fenum-extension/FenumDemo.java:57]:
```suggestion
        int int0 = TestStatic.CCONST1; // ok, @MyFenum applies by default in this method
        @NonNegative int int1 = TestStatic.BCONST1; // ok, @MyFenum applies by default in this method
```

Comment (wmdietl) [reply docs/examples/fenum-extension/FenumDemo.java:57]: Does the default get applied if there is a `@NonNegative`? If not, can you add it as a TODO and open a follow-up issue?

File: docs/examples/fenum-extension/qual/MyFenum.java [hunk 2]
```diff
@@ -13,4 +14,8 @@
 @Retention(RetentionPolicy.RUNTIME)
 @Target({ElementType.TYPE_USE, ElementType.TYPE_PARAMETER})
 @SubtypeOf(FenumTop.class)
+// This weird default is used in this example to test whether defaults are
+// correctly applied to both annotated and unannotated instances
+// (in this example, "short" and "@NonNegative short" (see issue #333).
```
Comment (wmdietl) [inline docs/examples/fenum-extension/qual/MyFenum.java:19]:
```suggestion
// (in this example, "short" and "@NonNegative short", see issue #333).
```

**Review by wmdietl — APPROVED** [review]
Thanks!
