### PR TITLE
Handle arguments to anonymous constructors in `convertCallArguments`

### LINKED ISSUE #400: error: AsSuperVisitor: type is not an erased subtype of supertype after version 3.21.3
Here is the test case:
```
class AnoymousAndInnerClass {
    class MyInnerClass {
        public MyInnerClass() {}

        public MyInnerClass(String s) {}

        public MyInnerClass(int... i) {}
    }

}

class Top {
    void test(AnoymousAndInnerClass outer) {
        outer.new MyInnerClass(1, 2, 3){};

    }
}
```

As far as I know, this issue only happens: 1. varargs 2.anonymous class

### PR DESCRIPTION
**Pull request by al3xliu**
1. Fix issue #400 by getting the actural receiver type of a new class from the synthetic argument when typing checking enclosing expressioon.
2. Clean up the redundant code of `constructorFromUse` and `adaptParameters`: don't add the receiver type to the paramterTypes and handle specical case for Java version below 11.
3. Fix the argument data structure of `ObjectCreationNode` by moving some code from `adaptParameters` to `CFGTranslationPhaseOne`. 

The reason why we use one PR to solve this two issues is they are very close: the code we don't use in `adaptParameters` is exact what `CFGTranslationPhaseOne` need.

Fixes #400.

### CODE REVIEW

**Comment by wmdietl** [comment]
@al3xliu Can you pick a better title and summary for this PR? It doesn't just add test cases, it also fixes something.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 1]
```diff
@@ -1269,13 +1269,15 @@ protected Node methodInvocationConvert(Node node, TypeMirror formalType) {
      * a list of {@link Node}s representing the arguments converted for a call of the method. This
      * method applies to both method invocations and constructor calls.
      *
+     * @param enclosingType a TypeMirror of the enclosing expression if appropriate
```
Comment (wmdietl) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1272]: Would `enclosingExprType` be a clearer name? Otherwise, a quick read of the name could make one think it's the type that contains this method.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 2]
```diff
@@ -1311,6 +1313,20 @@ protected List<Node> convertCallArguments(
             } else {
                 assert lastParamType instanceof ArrayType
                         : "variable argument formal must be an array";
+                // Handle anonymous constructors that extend a class with an enclosing type.
```
Comment (wmdietl) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1316]: Don't add comments that explain the history, explain the code as it is now.
The reference to AnnotatedTypes is confusing now, as there is no code to look at. It's not borrowed, it's moved from there to here.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 3]
```diff
@@ -1311,6 +1313,20 @@ protected List<Node> convertCallArguments(
...
+                // The logic is borrowed from AnnotatedTypes.adaptParameters(). However,
+                // adaptParameters
+                // does not need this part anymore after mering this PR.
+                if (method.getKind() == ElementKind.CONSTRUCTOR
+                        && method.getEnclosingElement().getSimpleName().contentEquals("")
```
Comment (wmdietl) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1321]:
```suggestion
                        && ((TypeElement) method.getEnclosingElement()).getNestingKind() == NestingKind.ANONYMOUS
```

Does this work? It's maybe a bit clearer than the string comparison.
We have a [helper method](https://github.com/eisop/checker-framework/blob/b235df2211833a32100d3a78c6100a0315fc1d48/javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java#L1715) for trees, but not for `ExecutableElement`s.
Is it worth looking whether this pattern is used elsewhere and replacing it with a new helper?

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 4]
```diff
@@ -1311,6 +1313,20 @@ protected List<Node> convertCallArguments(
...
+                        && enclosingType != null) {
+                    TypeMirror p0tm = formals.get(0);
+                    // We only care about Java 11+ since then the arguments do NOT include the
+                    // enclosing expression.
+                    if (types.isSameType(enclosingType, p0tm) && SystemUtil.jreVersion >= 11) {
```
Comment (wmdietl) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1326]: Do the simple int comparison first and then the type comparison.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 1 above)
Comment (wmdietl) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1272]: Explain when it is "appropriate" and when it is null.
It might be worth expanding on this in the documentation above.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 5]
```diff
@@ -3500,6 +3500,27 @@ protected void checkEnclosingExpr(NewClassTree node, AnnotatedExecutableType con
...
+                  Consider the following code:
+                  Class Outer {
+                      Class Inner{}
+                  }
+                  Class Top{
+                      void test(Outer outer) {
+                          outer.new Inner(){};
+                      }
+                  }
+                  In Java versions below 11, the argumentReceiverType of outer.new Inner(){} is Top instead of Outer, because java8 organizes
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3513]: So is it "below 11" or "java8"?

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 6]
```diff
@@ -3500,6 +3500,27 @@ protected void checkEnclosingExpr(NewClassTree node, AnnotatedExecutableType con
...
+                  newClassTree in a different way: there is a synthetic argument. Hence, use this synthetic argument when the underlying types are different.
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3514]: "Synthetic argument" for what?

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 7]
```diff
@@ -3500,6 +3500,27 @@ protected void checkEnclosingExpr(NewClassTree node, AnnotatedExecutableType con
...
+                * */
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3515]:
```suggestion
                */
```

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java [hunk 8]
```diff
@@ -2763,30 +2763,12 @@ public ParameterizedExecutableType constructorFromUse(NewClassTree tree) {
...
-                    // Because the anonymous constructor doesn't have annotated receiver type,
-                    // we copy the receiver type from the super constructor invoked in the anonymous
-                    // constructor and add it to the parameterTypes as the first element.
-                    con.setReceiverType(superCon.getReceiverType());
-                    p.add(con.getReceiverType());
-                } else {
-                    p.add(con.getParameterTypes().get(0));
-                }
-                p.addAll(1, superCon.getParameterTypes());
+                // Because the anonymous constructor doesn't have annotated receiver type,
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:2766]: The deleted comment contained an example. Would that example still be useful explanation somewhere?

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java [hunk 9]
```diff
@@ -968,37 +968,31 @@ public static List<AnnotatedTypeMirror> adaptParameters(
...
+            // below 11 since they have an extra enclosing expression argument
+            if (t.getEnclosingType() != null
+                    && SystemUtil.jreVersion < 11
+                    && args.size() > 0
+                    && atypeFactory.types.isSameType(
+                            t.getEnclosingType(),
+                            atypeFactory.getAnnotatedType(args.get(0)).getUnderlyingType())) {
+                List<AnnotatedTypeMirror> p = new ArrayList<>(parameters.size() + 1);
+                p.add(atypeFactory.getAnnotatedType(args.get(0)));
+                p.addAll(1, parameters);
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:987]: Is the `1` necessary? Plain `addAll` appends to the end and at this point `p` contains only one element anyways, right?

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java [hunk 10]
```diff
@@ -968,37 +968,31 @@ public static List<AnnotatedTypeMirror> adaptParameters(
...
-                        if (!atypeFactory.types.isSameType(TreeUtils.typeOf(args.get(0)), p0tm)) {
-                            // Remove the first parameter.
-                            parameters = parameters.subList(1, parameters.size());
-                        }
-                    }
-                }
-                if (parameters.isEmpty()) {
-                    return parameters;
-                }
+            // Let parameterTypes and arguments match, i.e., size, and we only handle Java versions
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:977]: Add some comment to the javadoc of this method what this is doing.

Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:977]: What do you mean with `Let parameterTypes and arguments match, i.e., size`? I don't see a size comparison.

Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:977]: A few lines above, I again see the `method.getElement().getEnclosingElement().getSimpleName().contentEquals("")` before your edits.
Please look for that pattern and introduce a nicer helper function for that.

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java [hunk 11]
```diff
@@ -968,37 +968,31 @@ public static List<AnnotatedTypeMirror> adaptParameters(
...
+            // below 11 since they have an extra enclosing expression argument
+            if (t.getEnclosingType() != null
+                    && SystemUtil.jreVersion < 11
+                    && args.size() > 0
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:981]:
```suggestion
                    && !args.isEmpty()
```

Isn't that simpler?

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks for all your improvements to this!
Add a changelog entry, in particular to highlight the change for users of the Dataflow Framework.
I see a test case for the [first test](https://github.com/eisop/checker-framework/issues/400#issuecomment-1431911987) in #400.
Is there a test for the second test case, where there is no varargs method?

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java (hunk 11 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:1033]: Thanks!

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 4 above)
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1326]: Thanks!

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java (hunk 9 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:1039]: Thanks.No, we don't need it.

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java (hunk 10 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:1029]: Thank! I reworded the comments in my local.

Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:1029]: Thanks! But I don't quite understand as we already have the revelant javadoc. Do you think the current is not enough?

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java (hunk 8 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:2829]: Yes, I think it can be kept here, do you agree?

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 6 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3573]: Thanks! Reworded the comment in my local.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 1 above)
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1272]: Thanks. Done in my local.

**Review by wmdietl — COMMENTED** [review]
The title of the PR is rather odd - what do you fix about the "data structure" of `ObjectCreationNode`? The PR isn't even touching that file.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 2 above)
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1316]: Thanks! I reworeded the comments.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 3 above)
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1321]: Thanks! Let me try first. I believe it is worth creating a new helper method like "isAnoymous" for a contructor ExecutableElement/

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java (hunk 10 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:1029]: Thanks!

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 1 above)
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java]: Sorry about that, I pushed it just now.

**Comment by al3xliu** [comment]
> The title of the PR is rather odd - what do you fix about the "data structure" of `ObjectCreationNode`? The PR isn't even touching that file.

Thanks. This PR fixes the data structure of ObjectCreationNode By changing the helper method `convertCallArguments`. I changed the title.

**Comment by al3xliu** [comment]
> Thanks for all your improvements to this! Add a changelog entry, in particular to highlight the change for users of the Dataflow Framework. I see a test case for the [first test](https://github.com/eisop/checker-framework/issues/400#issuecomment-1431911987) in #400. Is there a test for the second test case, where there is no varargs method?

Thanks. There is already a test for the second test case in https://github.com/eisop/checker-framework/blob/master/framework/tests/all-systems/AnoymousAndInnerClass.java

**Comment by wmdietl** [comment]
> Thanks. There is already a test for the second test case in https://github.com/eisop/checker-framework/blob/master/framework/tests/all-systems/AnoymousAndInnerClass.java

That doesn't seem possible. The comment in #400 says that the second test case also crashes.
So no test case for it can currently be in that file, otherwise it would fail.
The test cases this PR adds are all for vararg methods, not for a single primitive parameter like in the second test in #400.
What am I missing?

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 12]
```diff
@@ -1267,15 +1267,21 @@ protected Node methodInvocationConvert(Node node, TypeMirror formalType) {
     /**
      * Given a method element, its type at the call site, and a list of argument expressions, return
      * a list of {@link Node}s representing the arguments converted for a call of the method. This
-     * method applies to both method invocations and constructor calls.
+     * method applies to both method invocations and constructor calls. The constructor may need an
+     * extra enclosingExprType parameter when it is an inner class constructor with an explicit
+     * enclosing expression. The part of "Handle anonymous constructors" is moved from the helper
```
Comment (wmdietl) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1272]: Again, don't document what was or what happened, document what is the behavior now. Why would anyone care that some code was moved here? Document what the behavior is because that code was moved.

File: docs/CHANGELOG.md [hunk 13]
```diff
@@ -3,6 +3,9 @@ Version 3.33.0-eisop1 (April ?, 2023)
 
 **User-visible changes:**
 
+The format of the arguments of an `ObjectCreationNode` is correct when the node refers to an
+anonymous constructor with an explicit enclosing expression.
```
Comment (wmdietl) [inline docs/CHANGELOG.md:7]:
```suggestion
Corrected the arguments to an `ObjectCreationNode` when the node refers to an
anonymous constructor invocation with an explicit enclosing expression.
```

Comment (wmdietl) [reply docs/CHANGELOG.md:7]: This should move down to `Implementation details`.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 14]
```diff
@@ -3559,6 +3559,27 @@ protected void checkEnclosingExpr(NewClassTree node, AnnotatedExecutableType con
...
+                  Consider the following code:
+                  Class Outer {
+                      Class Inner{}
+                  }
+                  Class Top{
+                      void test(Outer outer) {
+                          outer.new Inner(){};
+                      }
+                  }
+                  In Java versions below 11, the argumentReceiverType of outer.new Inner(){} is Top instead of Outer, because java8 organizes
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3572]: Should the `java8` be something else?
If it should be `Java 8`, what about Java 9 and 10?
Or should it be `Java below 11` to be consistent with the first part of this sentence?

File: framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java (hunk 8 above)
Comment (wmdietl) [reply framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java:2838]: Sure, as long as the example clarifies how things work now, keep it.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 5 above)
Comment (wmdietl) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3572]: I just notice that I had the same comment again. Why did you just resolve this instead of addressing it??

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks! A bunch more comments.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 5 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3572]: Sorry, I think I wrongly clicked the resolve botton. Usually I address the comment in my local then I click resolve.

Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3572]: Done in my local.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 14 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3572]: Thanks! Done in my local.

File: docs/CHANGELOG.md (hunk 13 above)
Comment (al3xliu) [reply docs/CHANGELOG.md:7]: Thanks! Done in my local.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 12 above)
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1272]: Thanks! Done in my local

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 15]
```diff
@@ -1311,6 +1317,15 @@ protected List<Node> convertCallArguments(
             } else {
                 assert lastParamType instanceof ArrayType
                         : "variable argument formal must be an array";
+                // Handle anonymous constructors that extend a class with an enclosing type.
+                if (ElementUtils.isAnonymousConstructor(method) && enclosingExprType != null) {
+                    TypeMirror p0tm = formals.get(0);
+                    // We only care about Java 11+ since then the arguments do NOT include the
+                    // enclosing expression.
+                    if (SystemUtil.jreVersion >= 11 && types.isSameType(enclosingExprType, p0tm)) {
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java]: Thanks!  We have the test case where the receiver and the first parameter have the same type. So I just added some comments.

**Comment by al3xliu** [comment]
> That doesn't seem possible. The comment in #400 says that the second test case also crashes.

Yes, you're right. I added such test case in `Issue282.java` now.

File: javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java [hunk 16]
```diff
@@ -228,6 +229,20 @@ public static boolean isFinal(Element element) {
         return element.getModifiers().contains(Modifier.FINAL);
     }
 
+    /**
+     * Returns true if the element is an anonymous constructor.
+     *
+     * @return true if the element is an anonymous constructor
+     */
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java]: Thanks, let me do it in a separate pr.

File: javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java [hunk 17]
```diff
@@ -228,6 +229,20 @@ public static boolean isFinal(Element element) {
...
+    public static boolean isAnonymousConstructor(Element element) {
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java]: Yes, I did, but I didn't finnd other potential uses except the two places we mentioned in this pr. However, It is worth to have this method because it is conviniennt and maybe others will use it. I will do it in a separate pr.

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks!

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 18]
```diff
@@ -1311,6 +1317,24 @@ protected List<Node> convertCallArguments(
             } else {
                 assert lastParamType instanceof ArrayType
                         : "variable argument formal must be an array";
+                // Handle anonymous constructors that extend a class with an enclosing type.
+                // We only care about Java 11+ since then the arguments do NOT include the
+                // enclosing expression, while the enclosing expression may appear as the first
+                // parameter
+                // of the anonymous constructor invocation, so we need to adjust the lastArgIndex in
+                // order to expand
+                // varargs properly.
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java]: Thanks! I changed my comment.

File: framework/tests/h1h2checker/Issue282.java [hunk 19]
```diff
@@ -7,6 +7,10 @@ public class Issue282 {
 
     public class Inner {
         Inner(@H2S2 Issue282 Issue282.this) {}
+
+        Inner(String s) {}
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply framework/tests/h1h2checker/Issue282.java:11]: Thanks! I added the comment.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 20]
```diff
@@ -1311,6 +1317,24 @@ protected List<Node> convertCallArguments(
...
+                if (SystemUtil.jreVersion >= 11
+                        && enclosingExprType != null
+                        && method.getKind() == ElementKind.CONSTRUCTOR
+                        && ((TypeElement) method.getEnclosingElement()).getNestingKind()
+                                == NestingKind.ANONYMOUS) {
+                    TypeMirror p0tm = formals.get(0);
+                    // Exclude the case when the enclosingExprType is an implicit this
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1331]: I also added related test cases in AnomousAndInnerClass.java.

File: framework/tests/h1h2checker/Issue282.java [hunk 21]
```diff
@@ -37,3 +46,11 @@ public void test3(@H1S1 String a, @H1S1 String b, @H1S2 String c) {
         new InnerGeneric<@H1S1 String>(a, c);
     }
 }
+
+class Top {
+    void test(@H1Top @H2S2 Issue282 outer) {
+        outer.new Inner() {};
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply framework/tests/h1h2checker/Issue282.java:52]: Thanks! The implict and explicit cases are covered in AnomousAndInnerClass.java.

File: framework/tests/all-systems/AnoymousAndInnerClass.java [hunk 22]
```diff
@@ -5,6 +5,8 @@ public MyInnerClass() {}
         public MyInnerClass(String s) {}
 
         public MyInnerClass(int... i) {}
+
+        public MyInnerClass(AnoymousAndInnerClass... o) {}
```
Comment (al3xliu) [inline framework/tests/all-systems/AnoymousAndInnerClass.java:9]: test such case without varargs, just AnoymousAndInnerClass

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java [hunk 23]
```diff
@@ -1020,37 +1021,33 @@ public static List<AnnotatedTypeMirror> adaptParameters(
...
-                if (parameters.isEmpty()) {
-                    return parameters;
-                }
+            // Let the size of parameterTypes and arguments match since we make the comparison in
+            // commonAssignmentCheck later, and we only handle Java versions
+            // below 11 since they have an extra enclosing expression argument
+            if (t.getEnclosingType() != null
+                    && SystemUtil.jreVersion < 11
+                    && !args.isEmpty()
+                    && atypeFactory.types.isSameType(
```
Comment (al3xliu) [inline framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:1037]: Add comment about this condition

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 24]
```diff
@@ -3592,6 +3592,27 @@ protected void checkEnclosingExpr(NewClassTree node, AnnotatedExecutableType con
...
+                  Class Outer {
+                      Class Inner{}
+                  }
+                  Class Top{
+                      void test(Outer outer) {
+                          outer.new Inner(){};
+                      }
+                  }
+                  In Java versions below 11, the argumentReceiverType of outer.new Inner(){} is Top instead of Outer, because Java below 11 organizes
+                  newClassTree in a different way: there is a synthetic argument representing the enclosing expression type. Hence, use this synthetic argument when the underlying types are different.
```
Comment (al3xliu) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3606]: cut the line

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 25]
```diff
@@ -1311,6 +1317,24 @@ protected List<Node> convertCallArguments(
             } else {
                 assert lastParamType instanceof ArrayType
                         : "variable argument formal must be an array";
+                // Handle anonymous constructors that extend a class with an enclosing type.
+                // We only care about Java 11+ since then the arguments do NOT include the
+                // enclosing expression, while the enclosing expression may appear as the first
+                // parameter of the anonymous constructor invocation. In order to correctly expand
```
Comment (al3xliu) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1323]: not invocation

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 26]
```diff
@@ -1311,6 +1317,24 @@ protected List<Node> convertCallArguments(
...
+                        && enclosingExprType != null
+                        && method.getKind() == ElementKind.CONSTRUCTOR
+                        && ((TypeElement) method.getEnclosingElement()).getNestingKind()
+                                == NestingKind.ANONYMOUS) {
+                    TypeMirror p0tm = formals.get(0);
+                    // Exclude the case when the enclosingExprType is an implicit this as we
+                    // create the implicit this artificially and the first parameter is not
+                    // the enclosing expression.
+                    if (types.isSameType(enclosingExprType, p0tm)) {
+                        lastArgIndex--;
```
Comment (al3xliu) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1335]: add comment on the declaration of lastArgIndex

File: framework/tests/all-systems/AnoymousAndInnerClass.java (hunk 22 above)
Comment (al3xliu) [reply framework/tests/all-systems/AnoymousAndInnerClass.java:9]: solved.

File: framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java (hunk 23 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java:1037]: We don't need this condition since we checked the version.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 26 above)
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1335]: I reworded the comments.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 25 above)
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1323]: done.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 24 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3606]: Done.

File: framework/tests/all-systems/AnoymousAndInnerClass.java [hunk 27]
```diff
@@ -5,6 +5,10 @@ public MyInnerClass() {}
         public MyInnerClass(String s) {}
 
         public MyInnerClass(int... i) {}
+
+        public MyInnerClass(AnoymousAndInnerClass c) {}
```
Comment (AndrewShf) [inline framework/tests/all-systems/AnoymousAndInnerClass.java:9]: Typo: `Anonymous`. Can you refactor the class name and the file name?

**Review by AndrewShf — APPROVED** [review]
Well done! Other than the typo, can you add more information to document issue400? The command to trigger this bug.

File: framework/tests/all-systems/AnoymousAndInnerClass.java (hunk 27 above)
Comment (al3xliu) [reply framework/tests/all-systems/AnoymousAndInnerClass.java]: Thanks

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java [hunk 28]
```diff
@@ -3592,6 +3592,29 @@ protected void checkEnclosingExpr(NewClassTree node, AnnotatedExecutableType con
                 argumentReceiverType = atypeFactory.getAnnotatedType(node.getEnclosingExpression());
             } else {
                 argumentReceiverType = atypeFactory.getReceiverType(node);
+                /*
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3595]: Is there a reason to do this here instead of in `getReceiverType`?
Wouldn't other callers of `getReceiverType` also benefit from this transformation?

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks! A bunch more comments and let's talk through them next time.

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks! A bunch more comments and let's talk through them next time.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 29]
```diff
@@ -1267,15 +1268,20 @@ protected Node methodInvocationConvert(Node node, TypeMirror formalType) {
     /**
      * Given a method element, its type at the call site, and a list of argument expressions, return
      * a list of {@link Node}s representing the arguments converted for a call of the method. This
-     * method applies to both method invocations and constructor calls.
+     * method applies to both method invocations and constructor calls. The constructor may need an
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1271]: Thanks! It should be "takes" or "needs".

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 30]
```diff
@@ -1267,15 +1268,20 @@ protected Node methodInvocationConvert(Node node, TypeMirror formalType) {
...
+     * extra enclosingExprType parameter when it is an inner class constructor with an enclosing
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1272]: No, there is no such condition.

[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1272]: Thanks! It should be.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 31]
```diff
@@ -1267,15 +1268,20 @@ protected Node methodInvocationConvert(Node node, TypeMirror formalType) {
...
+     * expression, either explicit or not.
      *
+     * @param enclosingExprType a TypeMirror of the enclosing expression if there is an explicit
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1275]: Yes, "either explicit or not" just wants to emphasize even an implicit enclosing expression will be passed into this method. An artificial this node will be passed.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 32]
```diff
@@ -1311,6 +1317,25 @@ protected List<Node> convertCallArguments(
...
+                // its first parameter. To ensure we organize the varargs at the correct index,
+                // `lastArgIndex` should be decremented by one, compensating for the additional
+                // parameter of the enclosing expression.
+                if (SystemUtil.jreVersion >= 11
+                        && enclosingExprType != null
+                        && method.getKind() == ElementKind.CONSTRUCTOR
+                        && ((TypeElement) method.getEnclosingElement()).getNestingKind()
+                                == NestingKind.ANONYMOUS) {
+                    TypeMirror p0tm = formals.get(0);
+                    // Exclude the case when the enclosingExprType is an implicit this as we
```
[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1332]: Thanks! I want to say when "this" is implict I need to EXCLUDE such case, ortherwise I can handle the condition in general.

File: framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java (hunk 28 above)
Comment (al3xliu) [reply framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java:3595]: Thanks! I remember we couldn't do it. Let me try and explain.

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java (hunk 31 above)
[the remark this answers is not in the document]
Comment (al3xliu) [reply dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1275]: Change the comment "if explicit", it should be always

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 33]
```diff
@@ -1311,6 +1318,20 @@ protected List<Node> convertCallArguments(
             } else {
                 assert lastParamType instanceof ArrayType
                         : "variable argument formal must be an array";
+                // Handle anonymous constructors with an explicit enclosing expression.
+                // There is a mismatch between the number of parameters and arguments
+                // when following conditions are met:
+                // 1. Java version >= 11
+                // 2. the method is an anonymous constructor
+                // 3. the constructor is invoked with an explicit enclosing expression
```
Comment (wmdietl) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1326]: Add commas between and a period at the end of your list.

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks for all the fixes!

File: docs/CHANGELOG.md [hunk 34]
```diff
@@ -15,6 +15,10 @@ will make suppression behavior consistent with other checkers.
 
 **Implementation details:**
 
+Corrected the arguments to an `ObjectCreationNode` when the node refers to an
+anonymous constructor invocation with an explicit enclosing expression in Java11+.
```
Comment (wmdietl) [inline docs/CHANGELOG.md:19]:
```suggestion
anonymous constructor invocation with an explicit enclosing expression in Java 11+.
```

File: javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java [hunk 35]
```diff
@@ -1753,6 +1753,22 @@ public static boolean isAnonymousConstructor(final MethodTree method) {
         return typeElement.getNestingKind() == NestingKind.ANONYMOUS;
     }
 
+    /**
+     * Returns true if the passed constructor is anonymous and has explicit enclosing expression.
```
Comment (wmdietl) [inline javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java:1757]:
```suggestion
     * Returns true if the passed constructor is anonymous and has an explicit enclosing expression.
```

File: dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java [hunk 36]
```diff
@@ -1311,6 +1315,23 @@ protected List<Node> convertCallArguments(
             } else {
                 assert lastParamType instanceof ArrayType
                         : "variable argument formal must be an array";
+                // Handle anonymous constructors with an explicit enclosing expression.
+                // There is a mismatch between the number of parameters and arguments
+                // when following conditions are met:
+                // 1. Java version >= 11,
+                // 2. the method is an anonymous constructor,
+                // 3. the excutable element has varargs,
```
Comment (wmdietl) [inline dataflow/src/main/java/org/checkerframework/dataflow/cfg/builder/CFGTranslationPhaseOne.java:1323]:
```suggestion
                // 3. the executable element has varargs,
```

**Review by wmdietl — APPROVED** [review]
Fix typos. Maybe needs reformatting.
