### PR TITLE
Instanceof pattern variable nullness annotation checks

### LINKED ISSUE #1058: Instanceof pattern variables
There is a basic test [InstanceOfPatternVariable.java](https://github.com/eisop/checker-framework/blob/064d3279bfa8eeb3cf2c129152d5e75be2d840b1/checker/tests/nullness/java17/InstanceOfPatternVariable.java#L11) that ensures that instanceof pattern variables don't crash.

This should be extended with code like this:

````
        if (x instanceof @Nullable String n) {
            n.hashCode();
        }
        if (x instanceof @NonNull Number nn) {
            nn.hashCode();
        }
````

Compiling this with the Nullness Checker gives no warnings - `n` correctly is non-null.

If one removes the uses of `n` and `nn`, the Nullness Checker raises the following warnings:

````
checker/tests/nullness/java17/InstanceOfPatternVariable.java:18: error: [instanceof.nullable] instanceof is only true for a non-null expression
        if (x instanceof @Nullable String) {}
              ^
checker/tests/nullness/java17/InstanceOfPatternVariable.java:19: warning: [instanceof.nonnull.redundant] redundant @NonNull annotation on instanceof
        if (x instanceof @NonNull Number) {}
              ^
1 error
1 warning
````

I would expect the same warnings/errors when using instanceof pattern variables.

### PR DESCRIPTION
**Pull request by thisisalexandercook**
fixes #1058 by adding support for instanceof pattern variables to the nullness visitor.

### CODE REVIEW

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java [hunk 1]
```diff
@@ -6,6 +6,7 @@
 import com.sun.source.tree.ArrayTypeTree;
 import com.sun.source.tree.AssertTree;
 import com.sun.source.tree.BinaryTree;
+import com.sun.source.tree.BindingPatternTree;
```
Comment (wmdietl) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:9]: This class doesn't exist on Java < 16. So you have to use
[isBindingPatternTree](https://github.com/eisop/checker-framework/blob/4935c5d74e2a26a2d52859075a10ac1f9fa42aad/javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java#L2366) and then [BindingPatternUtils#getVariable](https://github.com/eisop/checker-framework/blob/4935c5d74e2a26a2d52859075a10ac1f9fa42aad/javacutil/src/main/java/org/checkerframework/javacutil/TreeUtilsAfterJava11.java#L55).

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java [hunk 2]
```diff
@@ -471,7 +474,27 @@ public Void visitInstanceOf(InstanceOfTree tree, Void p) {
...
+            BindingPatternTree bindingPattern = (BindingPatternTree) pattern;
+            VariableTree variable = bindingPattern.getVariable();
+            ModifiersTree modifiers = variable.getModifiers();
+
+            List<? extends AnnotationTree> annotationTrees = modifiers.getAnnotations();
+
+            List<? extends AnnotationMirror> annotations =
+                    TreeUtils.annotationsFromTypeAnnotationTrees(annotationTrees);
+
+            if (AnnotationUtils.containsSame(annotations, NULLABLE)) {
```
Comment (wmdietl) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:490]: Try to avoid the duplication with the code below.
Here, just extract the variable and then the below code should look whether the variable has modifiers. Or extract the annotations in two different ways, whichever is easier.
The error should only be raised in one place.

File: docs/CHANGELOG.md [hunk 3]
```diff
@@ -3,11 +3,14 @@ Version 3.42.0-eisop6 (January ??, 2025)
...
 
+The Nullness Checker now reports an error if any instanceof pattern variables are annotated with `@Nullable`
+and a redundant warning if they are annotated with `@NonNull`.
+
 **Implementation details:**
 
 **Closed issues:**
 
-eisop#1003, eisop#1033.
+eisop#1003, eisop#1033, eisop#1058
```
Comment (wmdietl) [inline docs/CHANGELOG.md:13]:
```suggestion
eisop#1003, eisop#1033, eisop#1058.
```

**Review by wmdietl — CHANGES_REQUESTED** [review]
Thanks!

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java [hunk 4]
```diff
@@ -471,16 +473,33 @@ public Void visitInstanceOf(InstanceOfTree tree, Void p) {
             // Handle them properly.
             return null;
         }
+
+        List<AnnotationMirror> annotations = new ArrayList<>();
```
Comment (wmdietl) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:477]: At the moment it looks like there are two places that might add something to `annotations`.
Aren't they actually mutually exclusive?

Can you try:
1) Do not initialize the variable here at all;
2) Set `annotations` instead of adding to it;
3) Set `annotations` to null to make it definitely initialized;
4) Guard the containsSame checks with an `annotations != null` check.

That would avoid the extra allocation of an `ArrayList` that in most cases isn't used at all and makes the flow more direct.

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java [hunk 5]
```diff
@@ -471,16 +473,33 @@ public Void visitInstanceOf(InstanceOfTree tree, Void p) {
...
-                checker.reportError(tree, "instanceof.nullable");
-            }
-            if (AnnotationUtils.containsSame(annotations, NONNULL)) {
-                checker.reportWarning(tree, "instanceof.nonnull.redundant");
+            annotations.addAll(TreeUtils.annotationsFromTree((AnnotatedTypeTree) refTypeTree));
+        }
+
+        Tree patternTree = TreeUtilsAfterJava11.InstanceOfUtils.getPattern(tree);
+        if (patternTree != null) {
+            if (TreeUtils.isBindingPatternTree(patternTree)) {
```
Comment (wmdietl) [inline checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java:485]: Can these two be combined?
```suggestion
        if (patternTree != null && TreeUtils.isBindingPatternTree(patternTree)) {
```

**Review by wmdietl — CHANGES_REQUESTED** [review]

File: checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java (hunk 4 above)
Comment (thisisalexandercook) [reply checker/src/main/java/org/checkerframework/checker/nullness/NullnessNoInitVisitor.java]: Yes, I think these two instances are mutually exclusive, but I was unsure of the best way to initialize `annotations`. I originally used the `List.Of()` method but then realized it was a Java 9 feature. 

The null solution works well. I opted for initializing `annotations` to null before entering the logic as it appeared to keep the logic concise.

**Review by wmdietl — APPROVED** [review]
Thanks!
